name: GuionViewer Build and Test

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  build-and-test:
    name: Build and Test GuionViewer
    runs-on: macos-26

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build GuionViewer
        run: |
          xcodebuild build \
            -project Examples/GuionViewer/GuionViewer.xcodeproj \
            -scheme GuionViewer \
            -configuration Release \
            -destination 'platform=macOS' \
            -derivedDataPath Examples/GuionViewer/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Build GuionViewerTests
        run: |
          xcodebuild build-for-testing \
            -project Examples/GuionViewer/GuionViewer.xcodeproj \
            -scheme GuionViewer \
            -configuration Debug \
            -destination 'platform=macOS' \
            -derivedDataPath Examples/GuionViewer/DerivedData \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Run GuionViewerTests
        run: |
          xcodebuild test-without-building \
            -project Examples/GuionViewer/GuionViewer.xcodeproj \
            -scheme GuionViewer \
            -configuration Debug \
            -destination 'platform=macOS' \
            -derivedDataPath Examples/GuionViewer/DerivedData \
            -only-testing:GuionViewerTests \
            -resultBundlePath Examples/GuionViewer/TestResults.xcresult \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Run GuionViewerUITests
        run: |
          xcodebuild test-without-building \
            -project Examples/GuionViewer/GuionViewer.xcodeproj \
            -scheme GuionViewer \
            -configuration Debug \
            -destination 'platform=macOS' \
            -derivedDataPath Examples/GuionViewer/DerivedData \
            -only-testing:GuionViewerUITests \
            -resultBundlePath Examples/GuionViewer/UITestResults.xcresult \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO

      - name: Upload test results (default branches only)
        if: always() && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            Examples/GuionViewer/TestResults.xcresult
            Examples/GuionViewer/UITestResults.xcresult
          retention-days: 30

      - name: Archive GuionViewer.app (default branches only)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        run: |
          # Find the built app - search in all Release configurations
          APP_PATH=$(find Examples/GuionViewer/DerivedData/Build/Products -name "GuionViewer.app" -type d | grep -E "(Release|Release-)" | head -n 1)

          if [ -z "$APP_PATH" ]; then
            echo "Error: GuionViewer.app not found"
            echo "Searching in:"
            find Examples/GuionViewer/DerivedData/Build/Products -type d -maxdepth 2
            exit 1
          fi

          echo "Found app at: $APP_PATH"

          # Create archive directory
          mkdir -p Examples/GuionViewer/Archive

          # Create a zip archive of the app
          cd $(dirname "$APP_PATH")
          zip -r GuionViewer.zip GuionViewer.app
          mv GuionViewer.zip $GITHUB_WORKSPACE/Examples/GuionViewer/Archive/

          echo "App archived successfully"

      - name: Upload GuionViewer.app artifact (default branches only)
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v4
        with:
          name: GuionViewer-app
          path: Examples/GuionViewer/Archive/GuionViewer.zip
          retention-days: 90
